### ISSUE TITLE
Ressources (CSS/JS/Images) don't load on the HTTPS version of the website

### ISSUE THREAD

**Issue by Luthaf** [i-pi/i-pi.github.io#2]
Trying to load https://ipi-code.org/ looks very bad because a lot of CSS/JS files are not loaded. The HTML source contains links like `http://ipi-code.org/assets/css/styles_feeling_responsive.css` that should be updated to use HTTPS i.e. `https://ipi-code.org/assets/css/styles_feeling_responsive.css`.

Looking quickly through this repo, I found links hardcoded in [_favicon.html](https://github.com/i-pi/i-pi.github.io/blob/02262419e885925c11dd41cd21fe76adc70de989/_includes/_favicon.html), but I could not find the link to `styles_feeling_responsive.css`.

**Comment by ceriottm** [comment]
Fixed.
